### PR TITLE
Enable ATOMIC_REQUESTS for local development

### PR DESCRIPTION
**Pull request by rlucioni**
Wraps views in a transaction to more closely mirror production config, and removes what would be a redundant `atomic()` context manager. Use of SQLite in conjunction with `ATOMIC_REQUESTS` prevents us from disabling `AUTOCOMMIT` locally.

@stephensanchez or @clintonb, could you please take a look at this? @wedaly, tagging you since we discussed use of the `atomic()` context manager earlier. Since we're using `ATOMIC_REQUESTS` now, the entire view is an atomic operation.

@feanil, FYI.

### CODE REVIEW

**Comment by clintonb** [comment]
:+1:

**Comment by stephensanchez** [comment]
:+1:

**Comment by rlucioni** [comment]
After further consideration, we've decided to leave `ATOMIC_REQUESTS` set to its default value (`False`). If view-level atomicity is necessary, we can explicitly decorate views with `@atomic`, which is preferable to assuming that all views operate within atomic blocks. To be clear, `AUTOCOMMIT` will still be disabled in production.

The changes in this PR are no longer necessary, so I'll go ahead and close it.

**Comment by rlucioni** [comment]
Reopening and merging now that we understand the need for atomic requests.

**Comment by rlucioni** [comment]
Pylint is reporting an `unused-import` false positive, but only when run by Travis. I'm going to close this PR again and open a new one to see if that fixes the issue.

**Pull request closed without merging**
