### PR TITLE
Fix course data migration.

### PR DESCRIPTION
**Pull request by stephensanchez**
@rlucioni @clintonb @feanil 
The original data migration did not have the correct structure for our initial product; only a parent product should have a product class. Removing the class for the child product.
Additionally, I had a helper function for fulfillment to find the parent's product class. This is not needed. AbstractProduct already has a helper function.

### CODE REVIEW

**Comment by rlucioni** [comment]
Looks good to me. Were you able to verify that this change allows the product's attributes (e.g., course ID) to be modified in-place?

**Comment by clintonb** [comment]
:+1:

**Comment by stephensanchez** [comment]
@rlucioni yep

**Comment by rlucioni** [comment]
:+1:

**Pull request merged**
